theme: jekyll-theme-architect
title: Shanghai Interscholastic Ethics Bowl 2020
description: February 10th, HSEFZ
show_downloads: true
github:
  zip_url: http://baidu.com
  tar_url: http://baidu.com
  owner_url: https://jinshuju.net/f/AE4ry6
